#!/bin/bash
echo "Running: docker-compose -f ../Docker/docker-compose.yml build --no-cache"
docker-compose -f ../Docker/docker-compose.yml build --no-cache workspace nginx php-fpm php-worker mysql phpmyadmin redis redis-webui swagger-ui swagger-editor