#!/bin/bash
echo "Running: docker-compose -f ../Docker/docker-compose.yml build --no-cache"
docker-compose -f ../Docker/docker-compose.yml build --no-cache --pull workspace nginx php-fpm php-worker mysql phpmyadmin redis swagger-ui swagger-editor