#!/bin/bash
echo "Running: docker-compose -f ../Docker/docker-compose.yml up -d workspace nginx php-fpm php-worker mysql phpmyadmin redis redis-webui swagger-ui swagger-editor"
docker-compose -f ../Docker/docker-compose.yml up -d workspace nginx php-fpm php-worker mysql phpmyadmin redis redis-webui swagger-ui swagger-editor