#!/bin/bash

# Display the command being run
echo "Running: docker-compose -f ../Docker/docker-compose.yml exec workspace bash"

# Execute the docker-compose command
docker-compose -f ../Docker/docker-compose.yml exec workspace bash
